version: '3.8'

services:
  m3u8proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    restart: always
    volumes:
      - ./logs:/var/log/m3u8proxy:rw
    environment:
      - WORKERS=4
      - TIMEOUT=300
      - MAX_REQUESTS=1000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3